config/routes.rb
Interview::Application.routes.draw do
  get "registrations/update"
  resources :participators

  devise_for :users, :controllers => {:registrations => "registrations"}
  root 'reports#index'

  resources :reports do
    member {post :send_mail}    
  end

  resources :reports

end

app/models/participator.rb
class Participator < ActiveRecord::Base
end

app/models/report.rb
class Report < ActiveRecord::Base
	validates :name, presence: true
	validates :position, presence: true
	validates :interview_date, presence: true
	validates :detail, presence: true
	validates :comments, presence: true
	validates :evaluation, presence: true
	validates :conclusion, presence: true
	validates :resume, presence: true

	mount_uploader :resume, ResumeUploaderUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/participators_controller.rb
class ParticipatorsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_participator, only: [:show, :edit, :update, :destroy]

  # GET /participators
  # GET /participators.json
  def index
    @participators = Participator.all
  end

  # GET /participators/1
  # GET /participators/1.json
  def show
  end

  # GET /participators/new
  def new
    @participator = Participator.new
  end

  # GET /participators/1/edit
  def edit
  end

  # POST /participators
  # POST /participators.json
  def create
    @participator = Participator.new(participator_params)

    respond_to do |format|
      if @participator.save
        format.html { redirect_to @participator, notice: 'Participator was successfully created.' }
        format.json { render action: 'show', status: :created, location: @participator }
      else
        format.html { render action: 'new' }
        format.json { render json: @participator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participators/1
  # PATCH/PUT /participators/1.json
  def update
    respond_to do |format|
      if @participator.update(participator_params)
        format.html { redirect_to @participator, notice: 'Participator was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @participator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participators/1
  # DELETE /participators/1.json
  def destroy
    @participator.destroy
    respond_to do |format|
      format.html { redirect_to participators_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participator
      @participator = Participator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participator_params
      params.require(:participator).permit(:name, :email, :enabled)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def update
   new_params = params.require(:user).permit(:username, :email_password)

   if new_params['email_password'].empty? 
     new_params.delete('email_password')
   end

   @user = User.find(current_user.id)
   if @user.update_without_password(new_params)
     set_flash_message :notice, :updated
     #sign_in @user, :bypass => true
     render "edit"
     #redirect_to after_update_path_for(@user)
   else
     render "edit"
   end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_report, only: [:show, :edit, :update, :destroy, :send_mail]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  def send_mail
    @recipients = ReportMailer.send_report(@report, current_user).deliver
    respond_to do |format|
      format.html { redirect_to @report, notice: "Send successfully" }
    end
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render action: 'show', status: :created, location: @report }
      else
        format.html { render action: 'new' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:name, :position, :interview_date, :detail, :comments, :evaluation, :conclusion, :resume)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/participators_helper.rb
module ParticipatorsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>面试反馈管理系统</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "面试反馈管理系统", "/", :class => "navbar-brand" %>
      </div>
      <% if user_signed_in? %>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
			<li><a href='/participators'>协同面试人</a></li>
			<li><a href='/reports'>面试反馈</a></li>
		</ul>
        <ul class="nav navbar-nav navbar-right">

	      <li><%= link_to current_user.username, '/users/edit' %></li>
	      <li class="active">
          <%= link_to 'Sign Out', destroy_user_session_path, method:
            :delete %>

      </li>

        </ul>
      </div>
      <% end %>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/participators/_form.html.erb
<%= form_for(@participator, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @participator.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@participator.errors.count, "error") %> prohibited this participator from being saved:</h4>

      <ul>
      <% @participator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :enabled, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :enabled, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/participators/edit.html.erb
<div class="page-header">
  <%= link_to participators_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @participator, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>编辑</h1>
</div>

<%= render 'form' %>

app/views/participators/index.html.erb
<div class="page-header">
  <%= link_to new_participator_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Participator
  <% end %>
  <h2>协同面试人（抄送人）</h2>
</div>

<div class="table-responsive">
  <table class="table table-condensed table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th class="text-center">Enabled</th>
            <th class="text-center">Name</th>
            <th class="text-center">Email</th>
            <th colspan='2' class="text-center">Action</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @participators) do |participator| %>
            <td><%= participator.enabled.humanize %></td>
            <td><%= participator.name %></td>
            <td><%= participator.email %></td>
        <td><%= link_to 'Edit', edit_participator_path(participator) %></td>
        <td><%= link_to 'Destroy', participator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/participators/new.html.erb
<div class="page-header">
  <%= link_to participators_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New participator</h1>
</div>

<%= render 'form' %>

app/views/participators/show.html.erb
<div class="page-header">
  <%= link_to participators_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_participator_path(@participator), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>协同面试人</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @participator.name %></dd>

  <dt>Email:</dt>
  <dd><%= @participator.email %></dd>

  <dt>Enabled:</dt>
  <dd><%= @participator.enabled.humanize %></dd>

</dl>

app/views/reports/_form.html.erb
<%= form_for(@report, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @report.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h4>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :position, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :position, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :interview_date, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :interview_date, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :detail, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :detail, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :comments, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :comments, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :evaluation, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :evaluation, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :conclusion, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :conclusion, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :resume, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :resume, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/reports/edit.html.erb
<div class="page-header">
  <%= link_to reports_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @report, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing report</h1>
</div>

<%= render 'form' %>

app/views/reports/index.html.erb
<div class="page-header">
  <%= link_to new_report_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Report
  <% end %>
  <h1>面试反馈</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-condensed table-bordered table-hover">
    <thead>
      <tr>
            <th class="text-center">Name</th>
            <th class="text-center">Position</th>
            <th class="text-center">Interview date</th>
        <th colspan='2' class="text-center">Action</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @reports) do |report| %>
            <td><%= link_to report.name, report %></td>
            <td><%= link_to report.position, report %></td>
            <td><%= link_to report.interview_date, report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %> </td> 
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/reports/new.html.erb
<div class="page-header">
  <%= link_to reports_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New report</h1>
</div>

<%= render 'form' %>

app/views/reports/show.html.erb
<div class="page-header">
  <h2><%= @report.position %> <%= @report.interview_date %></h2>
  <%= link_to send_mail_report_path, :method => :post, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-envelope"></span>
    Send Report
  <% end %>
  <%= link_to reports_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_report_path(@report), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h2><%= @report.name%></h2>
</div>

<dl class="dl-horizontal">

  <dt>面试经过</dt>
  <dd><%= simple_format(@report.detail.html_safe) %></dd>

  <dt>面试评价</dt>
  <dd><%= simple_format(@report.comments.html_safe) %></dd>

  <dt>候选人评价</dt>
  <dd><%= @report.evaluation %></dd>

  <dt>面试结论</dt>
  <dd><%= @report.conclusion %></dd>

  <dt>简历查看</dt>
  <!--<dd><%= link_to @report.resume.file.filename, @report.resume.url %></dd>-->
  <dd><%= link_to @report.name + '_' + @report.position + '_简历', @report.resume.url %></dd>

</dl>